### ISSUE TITLE
Unable to start scrolling on submenus

### ISSUE THREAD

**Issue by mattiasskog** [FrDH/mmenu-js#1126]
Hi,

I cannot seem to be able to start scolling the menu when touching the expanded submenus an iOS devices.

If I start scrolling on one of the main menu items so the menu is "moving" I can point to a submenu and continue scrolling. 
But if the menu is still I cannot start moving it by touching on a submenu.

My config looks like this:
```
var menu = new Mmenu(document.querySelector('#my-menu'),
                        {
                            "slidingSubmenus": false,
                            "extensions": [
                                "pagedim-black",
                                "position-front",
                                "multiline"
                            ],
                            "scrollBugFix": {
                                "fix": true
                            },
                             "navbar": {
                                 "add": false
                        }
                    });
```
the menu itself is the same as in the mmenu samples.

```
<nav id="my-menu">
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/work">Our work</a></li>
        <li>
            <span>About us</span>
            <ul>
                <li><a href="/about/history">History</a></li>
                <li>
                    <span>The team</span>
                    <ul>
                        <li><a href="/about/team/management">Management</a></li>
                        <li><a href="/about/team/sales">Sales</a></li>
                        <li><a href="/about/team/development">Development</a></li>
                    </ul>
                </li>
            </ul>
        </li>
        <li>
            <span>Services</span>
            <ul>
                <li><a href="/services/design">Design</a></li>
                <li><a href="/services/development">Development</a></li>
                <li><a href="/services/marketing">Marketing</a></li>
            </ul>
        </li>
        <li><a href="/contact">Contact</a></li>
    </ul>
</nav>
```

**Comment by FrDH** [comment]
Thanks, I'll look into this.
For now, Try if setting the `scrollBugFix` option to `false` helps: https://mmenujs.com/docs/core/scroll-bug-fix.html

**Comment by FrDH** [comment]
Sorry for the delay, but it should be fixed in version 8.5.8

**Comment by systemshock89** [comment]
Hello!
I have the same problem on version 8.5.13.
scrollBugFix option to false - does not solve the problem.
Version 8.5.8 also has this problem.
Normally works only in version 8.5.3 and below.

**Comment by systemshock89** [comment]
Hello!

My previous comment was incorrect and deleted.

I have the same problem on version 8.5.13.
On the mobile browser Chrome menu does not scroll.
scrollBugFix option to false - does not solve the problem.
Version 8.5.8 also has this problem.

On desktop Chrome if testing on mobyle devtools - only in version 8.5.4 it will normally scroll by the mouse wheel, or by touch.
And it only works if scrollBugFix : false.

my config:

```
document.addEventListener(
    "DOMContentLoaded", () => {
        // Mmenu
        new Mmenu( "#mmenu", {
            // options
            "slidingSubmenus": false,
            "scrollBugFix": {
                "fix": false
            },
            "navbar": false, 
            "extensions": [
                "border-full", 
                "multiline", 
                "pagedim-black", 
            ],
            "navbars": [
                {
                    "position": "top",
                    "content": Array.from(document.querySelector("#mmenu-top-buttons").children)
                },
                {
                    "use": (document.querySelector("#mmenu-socials") ? true : false),
                    "position": "bottom",
                    "content": (document.querySelector("#mmenu-socials") ? Array.from(document.querySelector("#mmenu-socials").children) : null)
                },
            ],
        }, {
            // configuration
            offCanvas: {
                page: {
                    selector: ".page"
                }
            },
            language: "ru"
        });
    }
);
```
